# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211221_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 21, 21, 45, 31, 582749), verbose_name='Опубликован'),
        ),
    ]
