# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211222_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 33, 43, 357689), verbose_name='Опубликована'),
        ),
    ]
