# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-23 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211223_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'Cтатья Блога', 'verbose_name_plural': 'статьи Блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 23, 11, 40, 1, 486794), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 23, 11, 40, 1, 487794), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
